language: c
before_install:
- sudo add-apt-repository "deb mirror://mirrors.ubuntu.com/mirrors.txt trusty main restricted universe multiverse" -y  
- sudo apt-get update
install: sudo apt-get install cython gfortran hdf5-tools libhdf5-serial-dev liblapack-dev libsundials-serial-dev python-numpy texlive
script: ./bootstrap && ./configure CC=gcc FC=gfortran && make && make check && make pdf
