language: c
before_install:
- sudo apt-get install cython gfortran libhdf5-dev liblapack-dev libsundials-serial-dev python-h5py python-numpy
script: ./bootstrap && ./configure CC=gcc FC=gfortran && make && make check
