name: build
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v3
    - run: nix-shell --run "./bootstrap && ./configure CC=gcc FC=gfortran && make && make check"
